# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lev's blog
email: levdavid1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my blog. There are many like it but this one is mine
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://levdavid.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: assets/sass
  style: compact
# baseurl: "/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site
author: Lev D Gorbunov
# street_address: 1234 Somewhere Road
city: New York City
state: NY
# zip_code: 55555
country: United States of America
# phone: (716) 555-5555

# Social settings
# 500px_url:
# facebook_url:
github_url: https://github.com/levdavid
github_username:  levdavid
linkedin_url: https://www.linkedin.com/in/lev-gorbunov-1bb98747/
goodreads_url: https://www.goodreads.com/user/show/91366516-lev-david

# Build settings
markdown: kramdown